<?php

namespace App\Services\Assets;

if(!defined('MAX_IMAGES_SIZE')) define('MAX_IMAGES_SIZE', 2000);

/**
 * BANNER DIMENSION
 */
if(!defined('HOME_BANNER_IMAGE_WIDTH')) define('HOME_BANNER_IMAGE_WIDTH', 1620);
if(!defined('HOME_BANNER_IMAGE_HEIGHT')) define('HOME_BANNER_IMAGE_HEIGHT', 1080);

/**
 * NEWS DIMENSION
 */
if(!defined('HOME_THUMBNAIL_NEWS_IMAGE_WIDTH')) define('HOME_THUMBNAIL_NEWS_IMAGE_WIDTH', 412);
if(!defined('HOME_THUMBNAIL_NEWS_IMAGE_HEIGHT')) define('HOME_THUMBNAIL_NEWS_IMAGE_HEIGHT', 293);

if(!defined('THUMBNAIL_NEWS_IMAGE_WIDTH')) define('THUMBNAIL_NEWS_IMAGE_WIDTH', 376);
if(!defined('THUMBNAIL_NEWS_IMAGE_HEIGHT')) define('THUMBNAIL_NEWS_IMAGE_HEIGHT', 573);

if(!defined('NEWS_DETAIL_IMAGE_WIDTH')) define('NEWS_DETAIL_IMAGE_WIDTH', 1044);
if(!defined('NEWS_DETAIL_IMAGE_HEIGHT')) define('NEWS_DETAIL_IMAGE_HEIGHT', 693);